modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Wooly-Trees/issues"
license="MIT"

[[mods]]
modId="woolytrees"
version="${file.jarVersion}"
displayName="Wooly Trees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wooly-trees"
authors="ShyNieke, Mrbysco"
description='''
Trees that grow wool
'''
[[dependencies.woolytrees]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.woolytrees]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"