modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Mrbysco/Wooly-Trees/issues"
license="MIT"

[[mods]]
modId="woolytrees"
version="${file.jarVersion}"
displayName="Wooly Trees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wooly-trees"
authors="ShyNieke, Mrbysco"
description='''
Trees that grow wool
'''
[[dependencies.woolytrees]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"
