modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Wooly-Trees/issues"
license="MIT"

[[mods]]
modId="woolytrees"
version="${file.jarVersion}"
displayName="Wooly Trees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wooly-trees"
authors="ShyNieke, Mrbysco"
description='''
Trees that grow wool
'''
[[dependencies.woolytrees]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.7,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.woolytrees]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.7.0-beta,)"
ordering="NONE"
side="BOTH"